name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r project/requirements.txt  # Ensure correct filename and path

    - name: Debug Installed Dependencies
      run: |
        pip freeze  # List all installed packages for debugging purposes

    - name: Run tests
      run: |
        chmod +x project/tests.sh  # Ensure the script is executable
        bash project/tests.sh
