name: Data Pipeline Workflow

on:
  push:
    branches:
      - main

jobs:
  data-pipeline:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python environment
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      # Step 3: Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r project/requirement.txt
          

      - name: Run MADE Automated test
        run: 
            bash project/tests.sh
